- include_tasks:
    file: actions/install.yml
    apply:
      tags:
        - install
  tags:
    - install

- include_tasks:
    file: actions/start.yml
    apply:
      tags:
        - start
  tags:
    - start

- include_tasks:
    file: actions/restart.yml
    apply:
      tags:
        - restart
  tags:
    - restart

- include_tasks:
    file: actions/stop.yml
    apply:
      tags:
        - stop
  tags:
    - stop