ketadb_node_workspace: "/home/keta/node_03"

ketadb_node_config:
  node.name: "node_03"  # 节点名称

  http.port: 19203           # http端口
  transport.tcp.port: 19303  # tcp端口

  node.master: "false" # 是否为master
  node.web: "false"    # 是否为web
  node.data: "true"   # 是否为data

  node.tag: "hot"     # 冷热温配置：hot|warm|cold